services:
    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_HOST=localhost
            - POSTGRES_USER=dev
            - POSTGRES_DB=teste
            - POSTGRES_PASSWORD=123456
        container_name: database
        restart: always

    rabbit:
        image: rabbitmq:3-management
        container_name: rabbit
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./dados:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=123456