import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { CSSProperties } from 'react';
import Nav from '@/components/client/nav';

config.autoAddCss = false;

const style: CSSProperties = {
    background: 'rgb(41,37,37)',
    color: 'rgba(255,255,255,0.5)',
    fontFamily: 'var(--font-geist-sans)',
    margin: '0',
    padding: '0',
};

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                style={style}
                className={`${geistSans.variable} ${geistMono.variable}`}
            >
                <Nav />
                {children}
            </body>
        </html>
    );
}
